CREATE DATABASE musicOnline
CHARACTER SET 'utf8'
COLLATE 'utf8_general_ci';
USE musicOnline;
CREATE TABLE USER (
	ID			INT AUTO_INCREMENT PRIMARY KEY,
	USERNAME	TEXT,
	PASSWORD	TEXT
)ENGINE=InnoDB DEFAULT CHARSET=utf8;