CREATE DATABASE musicOnline
CHARACTER SET 'utf8'
COLLATE 'utf8_general_ci';
USE musicOnline;
CREATE TABLE USER (
	ID			INT AUTO_INCREMENT PRIMARY KEY,
	USERNAME	TEXT,
	PASSWORD	TEXT
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE MUSIC (
	ID			INT AUTO_INCREMENT PRIMARY KEY,
	TITLE		TEXT,
	URL			TEXT,
	ARTIST		TEXT,
	ALBUM		TEXT,
	DURATION	INT
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE LOVEMUSIC (
	ID			INT AUTO_INCREMENT PRIMARY KEY,
	USERID		INT,
	MUSICID		INT
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE SERCHLOG (
	ID			INT AUTO_INCREMENT PRIMARY KEY,
	CONTENT		TEXT
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE `LOVEMUSIC` ADD Unique INDEX index_name (`USERID`,`MUSICID`)